SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `DBIFE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBIFE` ;

-- -----------------------------------------------------
-- Table `DBIFE`.`IFE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBIFE`.`IFE` (
  `clave_elector` VARCHAR(255) NOT NULL,
  `cod_barras` VARCHAR(200) NULL,
  `nombre` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`clave_elector`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
