-- MySQL Script generated by MySQL Workbench
-- Thu Feb 11 00:00:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBSistema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBSistema` ;

-- -----------------------------------------------------
-- Schema DBSistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBSistema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DBSistema` ;

-- -----------------------------------------------------
-- Table `DBSistema`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Partido` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Partido` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(150) NULL COMMENT '',
  `logo` VARCHAR(70) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Candidato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Candidato` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Candidato` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(100) NULL COMMENT '',
  `Partido_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Candidato_Partido_idx` (`Partido_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Candidato_Partido`
    FOREIGN KEY (`Partido_id`)
    REFERENCES `DBSistema`.`Partido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Administrador` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario` VARCHAR(150) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Jornada` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Jornada` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `inicio` DATETIME NULL COMMENT '',
  `fin` DATETIME NULL COMMENT '',
  `nombre` VARCHAR(100) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`lugar` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`lugar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `estado` INT NULL COMMENT '',
  `municipio` INT NULL COMMENT '',
  `localidad` INT NULL COMMENT '',
  `seccion` INT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Casilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Casilla` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Casilla` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `MAC` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `Jornada_id` INT NOT NULL COMMENT '',
  `lugar_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Casilla_Jornada1_idx` (`Jornada_id` ASC)  COMMENT '',
  INDEX `fk_Casilla_lugar1_idx` (`lugar_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Casilla_Jornada1`
    FOREIGN KEY (`Jornada_id`)
    REFERENCES `DBSistema`.`Jornada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Casilla_lugar1`
    FOREIGN KEY (`lugar_id`)
    REFERENCES `DBSistema`.`lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Voto` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Voto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `time` TIMESTAMP NULL COMMENT '',
  `Candidato_id` INT NOT NULL COMMENT '',
  `Casilla_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Voto_Candidato1_idx` (`Candidato_id` ASC)  COMMENT '',
  INDEX `fk_Voto_Casilla1_idx` (`Casilla_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Voto_Candidato1`
    FOREIGN KEY (`Candidato_id`)
    REFERENCES `DBSistema`.`Candidato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voto_Casilla1`
    FOREIGN KEY (`Casilla_id`)
    REFERENCES `DBSistema`.`Casilla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Funcionario_casilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Funcionario_casilla` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Funcionario_casilla` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(145) NULL COMMENT '',
  `huella` VARCHAR(300) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `Casilla_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Funcionario_casilla_Casilla1_idx` (`Casilla_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Funcionario_casilla_Casilla1`
    FOREIGN KEY (`Casilla_id`)
    REFERENCES `DBSistema`.`Casilla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBSistema`.`Votado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBSistema`.`Votado` ;

CREATE TABLE IF NOT EXISTS `DBSistema`.`Votado` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `clave_elector` VARCHAR(255) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
